config/routes.rb
Rails.application.routes.draw do

  scope "/deploymentdemo/" do
      resources :loans
      resources :teams

      get "about", to: "pages#about"
      post "token/:id" => "visitors#token", as: :token
      post "teams/:id/token" => "teams#token", as: :team_token

      resources :withdrawals
      resources :deposits
      resources :accounts
      mount Upmin::Engine => '/admin'

      devise_for :users
      resources :users

      get "console/:id" => "teams#console", as: :console

      get "shortcode/:id" => "teams#shortcode", as: :shortcode

      get "teams/:id/example1" => "teams#example1", as: :example1
      get "teams/:id/example2" => "teams#example2", as: :example2
      get "teams/:id/example3" => "teams#example3", as: :example3
      get "teams/:id/example4" => "teams#example4", as: :example4
      get "teams/:id/example5" => "teams#example5", as: :example5

      post "teams/:id/palettes" => "teams#palettes", as: :palettes  

      authenticated :user do
        root  to: 'teams#home', as: :authenticated
      end

      unauthenticated do
        root  to: 'visitors#index', as: :unauthenticated
      end

      root  to: 'visitors#index'

  end


 


end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base

belongs_to :user

belongs_to :account


end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController
  before_action :set_withdrawal, only: [:show, :edit, :update, :destroy]

  # GET /withdrawals
  # GET /withdrawals.json
  def index
    @withdrawals = Withdrawal.all
  end

  # GET /withdrawals/1
  # GET /withdrawals/1.json
  def show
  end

  # GET /withdrawals/new
  def new
    @withdrawal = Withdrawal.new
    if params["account_id"].present?
      @withdrawal.account_id = params["account_id"]
    end 
  end

  # GET /withdrawals/1/edit
  def edit
  end

  # POST /withdrawals
  # POST /withdrawals.json
  def create
    @withdrawal = Withdrawal.new(withdrawal_params)

    respond_to do |format|
      if @withdrawal.save
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully created.' }
        format.json { render :show, status: :created, location: @withdrawal }
      else
        format.html { render :new }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /withdrawals/1
  # PATCH/PUT /withdrawals/1.json
  def update
    respond_to do |format|
      if @withdrawal.update(withdrawal_params)
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully updated.' }
        format.json { render :show, status: :ok, location: @withdrawal }
      else
        format.html { render :edit }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /withdrawals/1
  # DELETE /withdrawals/1.json
  def destroy
    @withdrawal.destroy
    respond_to do |format|
      format.html { redirect_to withdrawals_url, notice: 'Withdrawal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdrawal
      @withdrawal = Withdrawal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdrawal_params
      params.require(:withdrawal).permit(:user_id, :account_id, :amount)
    end
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/withdrawals/_form.html.erb
<%= simple_form_for(@withdrawal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { value: current_user.id } %>
    <%= f.input :account_id, collection: current_user.accounts, :input_html => { value: @withdrawal.account_id }, :include_blank => false %>
    <%#= f.input :account_id, as: :hidden, :input_html => { value: @withdrawal.account_id } %> 
    <%= f.input :amount, placeholder: "0.00" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/withdrawals/edit.html.erb
<h1>Editing Withdrawal</h1>

<%= render 'form' %>

<%= link_to 'Show', @withdrawal %> |
<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Withdrawals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Account</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @withdrawals.each do |withdrawal| %>
      <tr>
        <td><%= withdrawal.user_id %></td>
        <td><%= withdrawal.account_id %></td>
        <td><%= withdrawal.amount %></td>
        <td><%= link_to 'Show', withdrawal %></td>
        <td><%= link_to 'Edit', edit_withdrawal_path(withdrawal) %></td>
        <td><%= link_to 'Destroy', withdrawal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Withdrawal', new_withdrawal_path %>

app/views/withdrawals/new.html.erb
<h1>New Withdrawal <br/>
</h1>
<hr/>
<%= render 'form' %>

<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/show.html.erb
<h1>
  <strong>User:</strong>
  <%= @withdrawal.user.email %>
</h1>

<p>
  <strong>Account:</strong>
  <%= link_to @withdrawal.account.number, @withdrawal.account %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @withdrawal.amount %>
</p>

<%= link_to 'Edit', edit_withdrawal_path(@withdrawal) %> |
<%= link_to 'Back', withdrawals_path %>