config/routes.rb
Rails.application.routes.draw do

  scope "/deploymentdemo/" do
      resources :loans
      resources :teams

      get "about", to: "pages#about"
      post "token/:id" => "visitors#token", as: :token
      post "teams/:id/token" => "teams#token", as: :team_token

      resources :withdrawals
      resources :deposits
      resources :accounts
      mount Upmin::Engine => '/admin'

      devise_for :users
      resources :users

      get "console/:id" => "teams#console", as: :console

      get "shortcode/:id" => "teams#shortcode", as: :shortcode

      get "teams/:id/example1" => "teams#example1", as: :example1
      get "teams/:id/example2" => "teams#example2", as: :example2
      get "teams/:id/example3" => "teams#example3", as: :example3
      get "teams/:id/example4" => "teams#example4", as: :example4
      get "teams/:id/example5" => "teams#example5", as: :example5

      post "teams/:id/palettes" => "teams#palettes", as: :palettes  

      authenticated :user do
        root  to: 'teams#home', as: :authenticated
      end

      unauthenticated do
        root  to: 'visitors#index', as: :unauthenticated
      end

      root  to: 'visitors#index'

  end


 


end

app/models/deposit.rb
class Deposit < ActiveRecord::Base

belongs_to :account
belongs_to :user


end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = Deposit.all
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
    if params["account_id"].present?
      @deposit.account_id = params["account_id"]
    end 
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposit was successfully created.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_params
      params.require(:deposit).permit(:user_id, :account_id, :amount)
    end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= simple_form_for(@deposit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { value: current_user.id } %>
    <%#= f.input :account_id, collection: current_user.accounts %>
    <%= f.input :account_id, collection: current_user.accounts, :input_html => { value: @deposit.account_id }, :include_blank => false %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deposits</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Account</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.user_id %></td>
        <td><%= deposit.account_id %></td>
        <td><%= deposit.amount %></td>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<h1>
  <%= @deposit.user.email %>
</h1>

<p>
  <strong>Account:</strong>
  <%= link_to @deposit.account.number, @deposit.account %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @deposit.amount %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>