config/routes.rb
Rails.application.routes.draw do

  scope "/deploymentdemo/" do
      resources :loans
      resources :teams

      get "about", to: "pages#about"
      post "token/:id" => "visitors#token", as: :token
      post "teams/:id/token" => "teams#token", as: :team_token

      resources :withdrawals
      resources :deposits
      resources :accounts
      mount Upmin::Engine => '/admin'

      devise_for :users
      resources :users

      get "console/:id" => "teams#console", as: :console

      get "shortcode/:id" => "teams#shortcode", as: :shortcode

      get "teams/:id/example1" => "teams#example1", as: :example1
      get "teams/:id/example2" => "teams#example2", as: :example2
      get "teams/:id/example3" => "teams#example3", as: :example3
      get "teams/:id/example4" => "teams#example4", as: :example4
      get "teams/:id/example5" => "teams#example5", as: :example5

      post "teams/:id/palettes" => "teams#palettes", as: :palettes  

      authenticated :user do
        root  to: 'teams#home', as: :authenticated
      end

      unauthenticated do
        root  to: 'visitors#index', as: :unauthenticated
      end

      root  to: 'visitors#index'

  end


 


end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? && !current_user.admin? %>
  <li><%= link_to current_user.team.name, current_user.team %></li>
<% end %>


<% if user_signed_in? %>

    <li><%= link_to current_user.accounts.first.name, current_user.accounts.first %></li>
<% end %>

      <% if user_signed_in? %>
        <li><%= link_to 'Edit Settings', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
  <% if user_signed_in? %>
      <% if current_user.try(:admin?) %>
        <li><%= link_to 'Admin', 'admin' %></li>
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
    <% end %>
<% if user_signed_in? && current_user.admin? %>

    <li><%= link_to "Teams", teams_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
      <%= link_to "", authenticated_path, class: 'navbar-brand logo' %>
      <%= link_to 'Bank of CaféX', authenticated_path, class: 'navbar-brand' %>
      <% else %>
       <%= link_to "", unauthenticated_path, class: 'navbar-brand logo' %>
      <%= link_to 'Bank of CaféX', unauthenticated_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav pull-right">  
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%#= link_to 'About', about_path %></li>
<li><%#= link_to 'New Account', new_account_path %></li>

app/views/layouts/agent.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bank" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bank" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="https://172.31.250.62:8443/assistserver/sdk/web/consumer/assist.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Loan Application</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(Loan.new) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%#= f.input :user_id, as: :hidden, html_input: {value: current_user.id} %>
            <%= f.input :amount %>
            <%= f.input :rate, as: :hidden %>
            <%= f.input :term %>
            <%= f.input :repayment, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>





  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bank" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bank" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
        
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Loan Application</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(Loan.new) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%#= f.input :user_id, as: :hidden, html_input: {value: current_user.id} %>
            <%= f.input :amount %>
            <%= f.input :rate, as: :hidden %>
            <%= f.input :term %>
            <%= f.input :repayment, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>




  </body>
</html>

app/views/layouts/plain.html.erb
       <%= yield %>

app/views/layouts/slate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bank" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bank" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Loan Application</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(Loan.new) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%#= f.input :user_id, as: :hidden, html_input: {value: current_user.id} %>
            <%= f.input :amount %>
            <%= f.input :rate, as: :hidden %>
            <%= f.input :term %>
            <%= f.input :repayment, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>


  </body>
</html>

app/views/layouts/superhero.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bank" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bank" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <% if current_user %>
    <script type="text/javascript" src='https://<%= current_user.team.fqdn %>/assistserver/sdk/web/consumer/assist.js'></script>
    <% end %>

  </head>
  <body>
      <div class="alert alert-warning hidden text-center" id="banner">Currently Co-browsing 
          <button id="endSupport" class="btn btn-sm btn-danger">End Support</button>
      </div>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
    <main role="main" class="container">

       <%= render 'layouts/messages' %>
       <%= yield %>
       <button class="btn btn-sm btn-danger pull-right hidden" id="endSupportButton">end support</button>
    </main>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Loan Application</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(Loan.new) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%#= f.input :user_id, as: :hidden, html_input: {value: current_user.id} %>
            <%= f.input :amount %>
            <%= f.input :rate, as: :hidden %>
            <%= f.input :term %>
            <%= f.input :repayment, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

$('#endSupportButton').on("click", function() {
  AssistSDK.endSupport();
});

var showCobrowseUI = function() {
    $('#endSupportButton').removeClass('hidden');
 }
  
AssistSDK.onInSupport = function() {
   // Show user extra UI as they’re in a Live Assist session
   showCobrowseUI();
};

AssistSDK.onCobrowseActive = function() {
  // Display indicator, log, etc.
   $("#banner").removeClass("hidden");

};

AssistSDK.onCobrowseInactive = function() {
    
    $("#banner").addClass("hidden");
};


$("#endSupport").on("click", function(e) {
  e.preventDefault();

  AssistSDK.endSupport();
});


</script>


  </body>
</html>

app/views/layouts/token.html.erb
       <%= yield %>