config/routes.rb
Rails.application.routes.draw do

  scope "/deploymentdemo/" do
      resources :loans
      resources :teams

      get "about", to: "pages#about"
      post "token/:id" => "visitors#token", as: :token
      post "teams/:id/token" => "teams#token", as: :team_token

      resources :withdrawals
      resources :deposits
      resources :accounts
      mount Upmin::Engine => '/admin'

      devise_for :users
      resources :users

      get "console/:id" => "teams#console", as: :console

      get "shortcode/:id" => "teams#shortcode", as: :shortcode

      get "teams/:id/example1" => "teams#example1", as: :example1
      get "teams/:id/example2" => "teams#example2", as: :example2
      get "teams/:id/example3" => "teams#example3", as: :example3
      get "teams/:id/example4" => "teams#example4", as: :example4
      get "teams/:id/example5" => "teams#example5", as: :example5

      post "teams/:id/palettes" => "teams#palettes", as: :palettes  

      authenticated :user do
        root  to: 'teams#home', as: :authenticated
      end

      unauthenticated do
        root  to: 'visitors#index', as: :unauthenticated
      end

      root  to: 'visitors#index'

  end


 


end

app/models/account.rb
class Account < ActiveRecord::Base

belongs_to :user

has_many :deposits

has_many :withdrawals

def balance

	@balance = 0

	self.deposits.each do |deposit|
		@balance = @balance + deposit.amount
	end

	self.withdrawals.each do |withdrawal|
		@balance = @balance - withdrawal.amount
	end

	return @balance

end

	def activity

	    @activity = []

	    self.deposits.each do |deposit|
	      @activity << deposit
	    end 

	    self.withdrawals.each do |withdrawal|
	      @activity << withdrawal
	    end 

	    @activity = @activity.sort_by &:created_at

	

	    return @activity

	end

	def values

		@values = []

	    self.activity.each do |action|

	      if action.class ==  Deposit
	      @values << action.amount
	      else 
	      @values << -action.amount
	      end

	    end   

		    s = 0
    		@values = @values.map{|e| s += e}

    		return @values
	end

    def dates

	    @dates = []

	    self.activity.each do |action|
	      @dates << action.created_at.to_formatted_s(:short).to_s
	    end      

	    @dates = @dates

	    return @dates

   end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin, only: :index

  require 'json'

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    @loan = Loan.new
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show

    @loan = Loan.new

    @activity = []

    @account.deposits.each do |deposit|
      @activity << deposit
    end 

    @account.withdrawals.each do |withdrawal|
      @activity << withdrawal
    end 

    @activity = @activity.sort_by &:created_at

    @values = []

    @activity.each do |action|

      if action.class ==  Deposit
      @values << action.amount
      else 
      @values << -action.amount
      end

    end   

    s = 0
    @values = @values.map{|e| s += e}

    @dates = []

    @activity.each do |action|
      @dates << action.created_at.to_formatted_s(:short).to_s
    end      

    @dates = @dates


  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def authorize_admin
      flash[:alert] = "You are not cool enough to do this - go back from whence you came."
      redirect_to root_path unless current_user.admin?
    #redirects to previous page
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :number, :name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :number %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>My Accounts</h1>
<hr/>
    <% current_user.accounts.each do |account| %>
        <h2><%= link_to "#{account.name} (#{account.number})", account %></h2>
        <%= link_to 'Edit', edit_account_path(account) %>
        <%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %>
        <hr/>
    <% end %>
<br>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<div class="col-md-12">

<div class="col-md-8">


<h1>
 <%= @account.name %> (<%= @account.user.name %>)
 <br/>
 <small>Number <%= @account.number %></small>
</h1>
<hr/>
<%= link_to 'Edit', edit_account_path(@account) %> | <%= link_to 'Deposit', new_deposit_path(account_id: @account.id) %> | <%= link_to 'Withdrawal', new_withdrawal_path(account_id: @account.id) %>

<h2>Balance: £<%= number_with_precision(@account.balance, :precision => 2) %></h2>
<br/>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#activity" aria-controls="activity" role="tab" data-toggle="tab">Activity</a></li>
    <li role="presentation"><a href="#graph" aria-controls="graph" role="tab" data-toggle="tab">Graph</a></li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="activity">
    	<br/>
    	<div class="list-group">
			<% @activity.reverse.each do |action| %>
				<% if action.class == Deposit %>
				<a href="<%= deposit_path(action.id) %>" class="list-group-item list-group-item-success">
					£<%= number_with_precision(action.amount, :precision => 2) %> - <%= action.created_at.to_formatted_s(:short) %>
				</a>
				<% else %>
				<a href="<%= withdrawal_path(action.id) %>" class="list-group-item list-group-item-danger">
					£-<%= number_with_precision(action.amount, :precision => 2) %> - <%= action.created_at.to_formatted_s(:short) %>
				</a>
				<% end %>
			<% end %>

		</div>

    </div>
    <div role="tabpanel" class="tab-pane" id="graph">
    	
    <canvas id="myChart" width="400" height="400"></canvas>


    </div>
  </div>

</div>

<div class="col-md-4">
	
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-block pull-right" data-toggle="modal" data-target="#myModal">
  Apply for a Loan
</button>
</div>


</div>
<script type="text/javascript">
	
	var ctx = document.getElementById("myChart");
	var ctx = document.getElementById("myChart").getContext("2d");
	var ctx = $("#myChart");

	var dates = "<%= @dates.to_json %>";


	var dates = JSON.parse(dates.replace(/&quot;/g,'"'));
	// console.log($.makeArray(dates));

	var data = {
		    labels: dates,
		    datasets: [
		        {
		            label: <%= @account.number %>,
		            fill: false,
		            lineTension: 0.1,
		            backgroundColor: "rgba(75,192,192,0.4)",
		            borderColor: "rgba(75,192,192,1)",
		            borderCapStyle: 'butt',
		            borderDash: [],
		            borderDashOffset: 0.0,
		            borderJoinStyle: 'miter',
		            pointBorderColor: "rgba(75,192,192,1)",
		            pointBackgroundColor: "#fff",
		            pointBorderWidth: 1,
		            pointHoverRadius: 5,
		            pointHoverBackgroundColor: "rgba(75,192,192,1)",
		            pointHoverBorderColor: "rgba(220,220,220,1)",
		            pointHoverBorderWidth: 2,
		            pointRadius: 1,
		            pointHitRadius: 10,
		            data: <%= @values %>,
		        }
		    ]
		};


	var myLineChart = Chart.Line(ctx, {
   	 data: data,
   	});


</script>